# Generated by Django 3.2.4 on 2021-06-11 09:00

from django.db import migrations


def populate_pet_types(apps, schema_editor):
    PetType = apps.get_model('pets', 'PetType')
    for pet_type in ['Dog', 'Cat']:
        new_type = PetType(name=pet_type)
        new_type.save()

def populate_pet_breeds(apps, schema_editor):
    PetBreed = apps.get_model('pets', 'PetBreed')
    for pet_breed in ['German Shepherd', 'Pitbull', 'Bulldog']:
        new_breed = PetBreed(name=pet_breed)
        new_breed.save()
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_pet_types),
        migrations.RunPython(populate_pet_breeds),
    ]
